USE actors;

UPDATE actores_por_id SET patrimonio = 198000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000001;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000001, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1122000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000002;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000002, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 2772000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000003;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000003, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 422400.0 WHERE id_actor = a0000000-0000-0000-0000-000000000004;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000004, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 792000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000005;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000005, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 541200.0 WHERE id_actor = a0000000-0000-0000-0000-000000000006;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000006, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 4620000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000007;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000007, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 330000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000008;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000008, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 950400.0 WHERE id_actor = a0000000-0000-0000-0000-000000000009;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000009, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 765600.0 WHERE id_actor = a0000000-0000-0000-0000-000000000010;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000010, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1584000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000011;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000011, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1188000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000012;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000012, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 594000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000013;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000013, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 369600.0 WHERE id_actor = a0000000-0000-0000-0000-000000000014;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000014, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 2376000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000015;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000015, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 2904000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000016;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000016, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1254000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000017;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000017, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1003200.0 WHERE id_actor = a0000000-0000-0000-0000-000000000018;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000018, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 1452000.0 WHERE id_actor = a0000000-0000-0000-0000-000000000019;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000019, 'secundario', 1, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

UPDATE actores_por_id SET patrimonio = 171600.0 WHERE id_actor = a0000000-0000-0000-0000-000000000020;
INSERT INTO personajes_por_actor (id_actor, rol, cantidad_de_apariciones, nombre_personaje, produccion, tipo_produccion, generos) VALUES (a0000000-0000-0000-0000-000000000020, 'principal', 3, 'Voz Misteriosa', 'Sansa Ball Race', 'profesional', {'Animacion', 'Aventura'});

